### ISSUE TITLE
Problem with Varnish 4 and PURGE

### ISSUE THREAD

**Issue by VicenteIranzoMaestre** [plone/plone.cachepurging#8]
Hello,

I have as Caching proxies , and VirtualHostMonster enabled
http://10.4.206.119:9001
http://10.4.206.120:9001
http://10.4.206.121:9001
http://10.4.206.122:9001

And when I edit a document I can see the PURGE request in varnishlog. But it doesn't work.

I have my facing domains filled in the controlpanel.

I can see the PURGE request on varnishlog and everything seems correct, but the cache doesn't get purged.

I've managed to purge Varnish with httpie sending the request through the normal url (not connecting directly to varnish port).

The main difference between one request and the other is the Host: header. When the host header matches the web host, then the purge works.

As a workaround I can configure my F5 to send a purge in all our nginx when it receives a PURGE call (in this case it woulb be doing a broadcast instead of balancing).

I've also configured my varnish in vcl_recv with a handle to the BAN request method so it bans the url without the host.

Am I doing missing something, or maybe the purge doesn't work when connecting directly to varnish port?

**Comment by gforcada** [comment]
_5 years later..._

I hope you could find a solution 🍀 in the meantime, Varnish released quite a few new versions and currently the only supported ones are 6.x and 7.x releases.

Feel free to reopen the issue if it is still affecting you on a newer Plone version (5.2 or upcoming 6.0) and can be reproduced with a newer varnish version.

**Comment by gforcada** [comment]
Forgot to close 😓
